spring:
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

app:
  jwt:
    cookie-secure: false
  carga-masiva:
    enabled: true
    tamano-lote: 25
    cantidad-clientes: 40
